[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --noinput", "python manage.py migrate --noinput"]

[start]
cmd = "daphne -b 0.0.0.0 -p $PORT edusphere_project.asgi:application"
